### ISSUE TITLE
Resize still fires after calling destroy

### ISSUE THREAD

**Issue by basisworldwide** [jedrzejchalubek/glidejs#156]
From what I see in the code, Events.prototype.unbind calls: uses Glide._uid, 
while the constructor defines this.uuid.

possible bug?

**Comment by jedrzejchalubek** [comment]
Please show code lines in lastest realase there is uuid in both places.

**Comment by edank** [comment]
src/modules/Events.js line 245
https://github.com/jedrzejchalubek/glidejs/blob/master/src/modules/Events.js

**Comment by jedrzejchalubek** [comment]
Confrim. Fixed 2eac314.
