### ISSUE TITLE
Let me define my own item widths

### ISSUE THREAD

**Issue by thasmo** [jedrzejchalubek/glidejs#163]
One feature would make this a heck of a carousel/slider plugin. It would be awesome if I can set the item width via CSS and Glide should calculate the items' positions based on that. This would enable items with different widths and it would make it a lot easier to define how many items are shown. The `paddings` option is only helpful when using `centered` to center/show a single item. In my case I want to show 4 items on a large screen and 1 item on a small screen. Currently I can't change the number of items shown on different widths efficiently because I can't change the width via CSS.

**Comment by marcwieland95** [comment]
Do you mean something similar like Owl Carousel provides?
http://www.owlcarousel.owlgraphic.com/demos/responsive.html

**Comment by jedrzejchalubek** [comment]
I'm aware of functional limitations on this side, it would be nice feature. Hovever, this would require big changes in `Run` and `Animate` module, so unfortunately, it is long term vision.

**Comment by Tomgroot** [comment]
@jedrzejchalubek Maybe, a setting min-width for the glide__slide divs. That would solve the problem from the unresponsive paddings. Often on smaller screens, with a high padding, the divs are way to small.

**Comment by jedrzejchalubek** [comment]
Version 3.0.0 will have the ability to display multiple slides on view, as well as responsive settings. Feature requests for version 2.0 are suspended. Closing, sorry.
