### ISSUE TITLE
Memory Optimized

### ISSUE THREAD

**Issue by 3zzy** [jedrzejchalubek/glidejs#164]
Thanks for your efforts, its a near perfect slider just that I wish instead of loading all the slides in the DOM it used three elements in the DOM to show prev, current, and next and use them to show all the slides much like PhotoSwipe:

> - PhotoSwipe keeps only three images in the DOM at once, because each “slide” is a composited layer, which consumes quite a lot of memory.
> - Almost no memory is consumed until the gallery is first opened.
> - The script has been tested for memory leaks. Navigating images back and forth and creating or deleting a gallery doesn’t leave a trace in memory.

I can try implementing this if someone could give any pointers.

Thanks

**Comment by arjunmenon** [comment]
Loading all in DOM is a bad idea.
Also, what about loading content dynamically? Many cases, you want to show more images/content in slider based on user action. Suppose in a gallery, some content is fetched remotely based on some condition, that should be later added to slider.

**Comment by jedrzejchalubek** [comment]
It will require a fundamental refactor in the base logic of a plugin. Even if it will be a good change, I would not have time to make such radical changes. Closing, sorry.
