### ISSUE TITLE
beforeTransition nextIndex parameter

### ISSUE THREAD

**Issue by creativ073** [jedrzejchalubek/glidejs#171]
Hi Jędrzej,
in the beforeTransition event there is a data parameter with the current slide index, but is not possible to know the next slide index, that one of the next current slide at the end of the transition.

It would be really useful in order to set action at the start of the transition based on which slide will be the next one.

Thank you,
Andrea Colanicchia.

**Comment by jedrzejchalubek** [comment]
Version 3.0.0 is coming. Feature requests for version 2.0 are suspended. Closing, sorry.
