### ISSUE TITLE
Title / description text on top of the image?

### ISSUE THREAD

**Issue by krishaamer** [jedrzejchalubek/glidejs#175]
Hey @jedrzejchalubek, thank you for the amazing work!

I was wondering what's the best cross-browser approach to adding a caption or title on top of the images. Any advice would be appreciated.

Best,
Kris

**Comment by jedrzejchalubek** [comment]
It depends on project design. I don't think slider itself will prevent you from any of solutions, but standard `position: relative` on slide content wrapper and caption positioned with `position: absolute` should do the job in a most of cases.
