### ISSUE TITLE
last release on cdn

### ISSUE THREAD

**Issue by yoanmarchal** [jedrzejchalubek/glidejs#176]
Could you update the last release on fastcdn ?
cause on fastcdn the last version is 2.0.4

**Comment by jedrzejchalubek** [comment]
I don't have control over these CDNs. Maybe you can use another CDN? Where script is up to date like https://cdnjs.com/libraries/Glide.js

**Comment by yoanmarchal** [comment]
thanks

**Comment by haroldao** [comment]
thanks
