### ISSUE TITLE
Missing options to add

### ISSUE THREAD

**Issue by maofree** [jedrzejchalubek/glidejs#179]
Hi
I like glidejs but I think some nice features are missing:
enable or remove prev and next with a simple option with true or false
the same for the dots, like happen with other carousels
set the items number without paddings for each classic default breakpoint like owl carousel orv slidesToShow for slick for responsive devices.
https://owlcarousel2.github.io/OwlCarousel2/demos/responsive.html
I've seen other requests about these points I tried to summarize them in a single post
I prefer glidejs but at this moment I cannot use it

thanks
bye

**Comment by jedrzejchalubek** [comment]
Hello. There is no direct API method for this. However, it can be done with little of javascript and `.refresh()` method. 

There is an example in `examples/destroy.html` file.
https://github.com/jedrzejchalubek/glidejs/blob/master/examples/destroy.html#L83-L90
