### ISSUE TITLE
Randomize data + Ajax

### ISSUE THREAD

**Issue by 1eddy87** [jedrzejchalubek/glidejs#180]
Is there a way to randomize the data that is shown?

Can we use Ajax to add more slides?

**Comment by jedrzejchalubek** [comment]
An answer to both questions is yes, this can be done with help of glide API. The detailed way is more directed by your situation and current implementation.

Here are basic example of dynamic inserting new slides:
https://github.com/jedrzejchalubek/glidejs/blob/master/examples/destroy.html#L83-L90
