### ISSUE TITLE
Wrong height calculation while using lazy loading with noscript fall back

### ISSUE THREAD

**Issue by Jeppeskovsgaard** [jedrzejchalubek/glidejs#187]
On all my websites I'm using WP Rocket lazy load and outputting most of the images using wp_get_attachment_image and a wrapper function.

This lazy load scripts adds a noscript fallback, but that causes glide.js to initially render the height of the slideshow twice the size.

Any update to the viewport (making it smaller og sliding) corrects the size.

You can see a small video of the problem here: https://www.screenmailer.com/v/R0GxtAsQaT8aVpQ

**Comment by jedrzejchalubek** [comment]
It's really a case-specific problem how loading is handled by this plugin. It's most likely to be a problem on WP plugin side. I cannot really help without access to the described environment.
