### ISSUE TITLE
"glide" undefined

### ISSUE THREAD

**Issue by italomaia** [jedrzejchalubek/glidejs#191]
I'm trying to use glidejs from npm with vuejs; I'm adding jquery with ProvidePlugin and import glide in my code; the thing is that when I try to use glide, the function is not available. Suggestions?

**Comment by jedrzejchalubek** [comment]
Show your webpack cofiguration and how you are importing glide. 

Unfortunately, Glide 2.* is not prepared to be used with js bundlers.

**Comment by jedrzejchalubek** [comment]
Bundlers support is coming with version `3.0.0`.
